# Generated by Django 5.2.3 on 2025-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0003_remove_candidate_id_candidate_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='ballot/candidate_images/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='logo_path',
            field=models.ImageField(blank=True, upload_to='ballot/logos/'),
        ),
    ]
